# Generated by Django 2.1.4 on 2019-02-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone',
            field=models.IntegerField(blank=None, default=None, max_length=11),
        ),
    ]
