# Generated by Django 2.1.4 on 2019-02-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_user_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
